version: "3"
services:
  web:
    build: .
    # container_name: py_placeholder
    command: flask run -h 0.0.0.0
    volumes:
      - .:/src
    ports:
      - 5000:5000
    # environment:
    #   FLASK_DEBUG: 1
    #   FLASK_ENV: development
    #   FLASK_SERVER_NAME: 0.0.0.0:5000
