version: "3"
services:
  web:
    build: .
    volumes:
      - .:/src:cached
    # command: python3 app.py
    ports:
      - 5000:5000
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_SERVER_NAME: 0.0.0.0:5000
